version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "emailer-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fp78037bnlsi"
s3_prefix = "emailer-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

